name: Simple Build

on:
  push:
    branches: [ category-ordering ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Install Jenkins HPI Plugin
      run: |
        # Create settings.xml with Jenkins repositories
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml << EOF
        <settings>
          <pluginGroups>
            <pluginGroup>org.jenkins-ci.tools</pluginGroup>
          </pluginGroups>
          <profiles>
            <profile>
              <id>jenkins</id>
              <repositories>
                <repository>
                  <id>repo.jenkins-ci.org</id>
                  <url>https://repo.jenkins-ci.org/public/</url>
                </repository>
              </repositories>
              <pluginRepositories>
                <pluginRepository>
                  <id>repo.jenkins-ci.org</id>
                  <url>https://repo.jenkins-ci.org/public/</url>
                </pluginRepository>
              </pluginRepositories>
            </profile>
          </profiles>
          <activeProfiles>
            <activeProfile>jenkins</activeProfile>
          </activeProfiles>
        </settings>
        EOF
        
        # Install the Jenkins HPI Plugin directly
        mvn org.apache.maven.plugins:maven-dependency-plugin:3.3.0:get -Dartifact=org.jenkins-ci.tools:maven-hpi-plugin:3.16
    
    - name: Update POM
      run: |
        # Add repositories to pom.xml if not already there
        if ! grep -q "<repositories>" pom.xml; then
          sed -i '/<\/project>/i \
          <repositories>\
            <repository>\
              <id>repo.jenkins-ci.org</id>\
              <url>https://repo.jenkins-ci.org/public/</url>\
            </repository>\
          </repositories>\
          <pluginRepositories>\
            <pluginRepository>\
              <id>repo.jenkins-ci.org</id>\
              <url>https://repo.jenkins-ci.org/public/</url>\
            </pluginRepository>\
          </pluginRepositories>' pom.xml
        fi
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dchangelist=1.0.0-CUSTOM -Dhpi-plugin.version=3.16
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: categorized-view-plugin
        path: target/categorized-view.hpi
        retention-days: 7
