name: Simple Build

on:
  push:
    branches: [ category-ordering ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dchangelist=1.0.0-CUSTOM
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: categorized-view-plugin
        path: target/categorized-view.hpi
        retention-days: 7
